services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: devpass
    #volumes:
    #  - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
